Repository dphfox/Fusion, pull requests merged in 2023-02, with the labels that each got.

#165 Update Value.spec.lua
  test/State/Value.spec.lua
Labels: status: evaluating, area: internal

#199 Implement attribute support into New function.
  src/Instances/Attribute.lua
  src/Instances/AttributeChange.lua
  src/Instances/AttributeOut.lua
  src/Logging/messages.lua
  src/init.lua
  test/Instances/Attribute.spec.lua
  test/Instances/AttributeChange.spec.lua
  test/Instances/AttributeOut.spec.lua
  test/init.spec.lua
Labels: kind: enhancement, status: approved, area: roblox

#212 Update documentation to include new functions.
  docs/api-reference/instances/attribute.md
  docs/api-reference/instances/attributechange.md
  docs/api-reference/instances/attributeout.md
  docs/api-reference/instances/index.md
  docs/api-reference/state/observer.md
  mkdocs.yml
Labels: kind: docs, status: approved, area: state, area: roblox

#91 Improving our contributions document
  CONTRIBUTING.md
Labels: status: approved, kind: meta

#219 Update default properties to include 3D objects
  src/Instances/defaultProps.lua
Labels: kind: enhancement, status: approved, area: roblox

#223 Update Fusion's CI Workflow
  .github/workflows/ci.yml
  foreman.toml
Labels: status: approved, kind: meta
